### ISSUE TITLE
Airspy bit-packing support?

### ISSUE THREAD

**Issue by dram-dave** [csete/gqrx#302]
Airspy's latest firmware release (v1.0.0-rc6) now supports bit-packing ("packing ADC samples to 12bits instead of using 16bits, packing uses 25% less USB bandwidth versus No Packing").  Can this feature somehow be used in conjunction with gqrx?  This might help marginal computers/USB interfaces handle Airspy's 10 Ms/s rate.

**Comment by csete** [comment]
Have you tried it?
Since gqrx does not do any hardware interfacing there is not much we can do in gqrx. If bit packing has to be enabled, it has to be done in gr-osmosdr.

I doubt though that any computer not able to transfer the 10Msps rate will be able to run gqrx with that amount of data because I have seen the opposite.

**Comment by csete** [comment]
I looked in the libairspy source code and it seem it is disabled by default, so it has to be enabled. Still, the airspy API is not available to gqrx, so it can only be added through gr-osmosdr.

**Comment by martinzsmith** [comment]
new argument in the latests  gr-osmosd for the airspy pack=1

**Comment by csete** [comment]
I have updated the PPA last night so people using it should have this available now.

**Comment by csete** [comment]
I can confirm that adding pack=1 to the device string works, although often gqrx will not be able to reopen the Airspy and require a restart of the application.
