### ISSUE TITLE
show applied squelch level on waterfall diagramm

### ISSUE THREAD

**Issue by pointhi** [csete/gqrx#346]
it would be cool when the applied squelch level is displayed on the waterfall diagramm using a simple (transparent) line.

**Comment by csete** [comment]
Unfortunately, it takes a little more than drawing a line because the squelch level is different from the FFT level. The FFT show power / FFT bin (bandwidth / FFT size), whereas the squelch level is the power in the channel filter passband (i.e. dame level as shown in the signal strength indicator).

**Comment by csete** [comment]
The squelch level is now shown in the signal strength indicator widget.
