### ISSUE TITLE
bookmarks on audio spectrum

### ISSUE THREAD

**Issue by kukabu** [csete/gqrx#399]
Hello

Sometimes I see bookmarks on audio spectrum. Why?!
![gqrx](https://cloud.githubusercontent.com/assets/3668677/17391950/29b6904a-5a2b-11e6-965c-fcd128ce1780.png)

**Comment by csete** [comment]
Hi @kukabu 

Thanks for the report. We can certainly consider this to be a bug and I think I can fix it quite easily.

You see the bookmarks on the audio spectrum because it uses the same code as the main spectrum and we didn't think about disabling bookmarks in the audio spectrum. So, bookmarks at these very low frequencies show up there.

Good that you found this out because processing the bookmarks also uses CPU and there is no reason for that here.

**Comment by csete** [comment]
It should be fixed now.

**Comment by kukabu** [comment]
Thanks.
