### ISSUE TITLE
where i can find source gqrx raspberry pi3

### ISSUE THREAD

**Issue by stackprogramer** [csete/gqrx#446]
hi  i want to source gqrx for raspberry pi, is this source on github is possible use for raspberrypi3?
i want to built gqrx on raspberry from soucre.
best regards stackprogramer

**Comment by csete** [comment]
Hi @stackprogramer 

Gqrx on the RPI3 uses the same source code, i.e. the one here. But in order to make it run well on RPI2 and RPI3, I had to:

1. Build gcc compiler for RPI3 that can generate proper code. The one included in raspbian is not good enough.
2. Build all dependencies from source
3. Build gqrx from source

**Comment by stackprogramer** [comment]
thank you very much

**Comment by csete** [comment]
Do you need any more info or can we close this?

**Comment by stackprogramer** [comment]
thanks very much,i didn't test compile gqrx on raspberry,but it is hard to compile with processor raspberry 3,any way it will be take long times..............
any way thanks
