### ISSUE TITLE
Ubuntu 18.04 - "error while loading shared libraries: libQt5Network.so.5" error

### ISSUE THREAD

**Issue by Schwartz1952** [csete/gqrx#626]
Greetings.  I have recently installed a fresh copy of Ubuntu 18.04 LTS and followed the GQRX instructions listed [here](http://gqrx.dk/download/install-ubuntu).

Before I begin, my apologies, I am new to posting issues on Github and GQRX.  I believe after reading [this](http://gqrx.dk/user-support) document, I should post details on the Google forum.  Please let me know if I should change the way I am reporting an issue.

To make an issue I am experiencing known, here are some details:
- Ubuntu 18.04 LTS
- Installed using [these](http://gqrx.dk/download/install-ubuntu) instructions
- Devices used: N/A, because I cannot get GQRX to start
- Error received: "gqrx: error while loading shared libraries: libQt5Network.so.5: cannot open shared object file: No such file or directory"
  - To my knowledge, after a few hours of searching, this is not an issue that has been reported verbatim.
- Steps taken to resolve the error: I actually had fresh installed Ubuntu 18 yesterday and installed GNURadio from PyBOMBS.  I realized that I would also like to use GQRX, so I followed the listed steps to install it for Ubuntu.  After receiving the error I listed above, and being the Linux newb I am, I decided that maybe my PyBOMBS installation had messed something up, and decided to reinstall Ubuntu 18 with nothing to lose.  Before this reinstallation, I attempted to install all libqt5 libraries by the following command:
`sudo apt-get install libqt5*`
thinking that maybe something required for the software to run was not installed.  This didn't help either and I repeated this "libqt5*" install after a reinstallation of Ubuntu 18 to no avail.
- I am running Ubuntu on my desktop computer.  Specs: Core i5 processor at 3.5 Ghz, 16 GB of RAM and a Nvidia GTX graphics card (running open source drivers, I think).

Again, please let me know if I need to add more detail, or revise the way I am reporting this.  I'll know head over to Google Groups and ask for some technical support. : )  

Thank you.

EDIT: here is my Google Groups [post](https://groups.google.com/forum/#!topic/gqrx/aaJ8ycajh-Y).

**Comment by csete** [comment]
I can see how the instructions can be misunderstood, but the point was that people are welcome to use the mailing list _instead of_ opening an issue here. There is no need to do both as it only becomes confusing.

We use github issues to track the status of bugs and feature requests, but not technical support issues - those belong on the mailing list. Since we have verified that the gqrx packages work on Ubuntu 18.04, I don't think your problems are because of a bug in the software or the package. So I am closing this issue and we continue the support on the mailing list.
