### ISSUE TITLE
Issue: GQRX Does not handle multiple FCD's Correctly using OsmoSDR

### ISSUE THREAD

**Issue by AndrewBraunEE** [csete/gqrx#648]
This could be a OsmoSDR issue as they've had an issue with setting the <device-index> correctly for the HackRF, but currently in GQRX, running two instances of GQRX with two different Funcube Dongles and setting the parameter 'fcd=0' or 'fcd=1' usually will display (garbage?) for the second GQRX instance that was instantiated. Normally you should be able to run 'fcd = <device-index>' and it should select the correct funcube.
https://osmocom.org/projects/gr-osmosdr/wiki
My presumption is that the issue is related to either GQRX or osmosdr being unable to correctly find the device, considering there would be two devices with the same product / vender id.

Any comments would be gladly appreciated, and I'd be happy to find a work-around if anyone can also debug the issue.

**Comment by csete** [comment]
There is absolutely nothing we can do about this in gqrx.

I suspect the backend was never written to handle two FCD devices for the simple reason that it makes little sense to use more than one FCD on the same machine since you can not see the difference between two devices, i.e. it is arbitrary which device is enumerated as device 0 and 1, and it can change between reboots. This applies both to the control and the audio interface of the FCD. For other devices you can use the serial number, but not for the FCD.

Please use the [support forum](http://gqrx.dk/user-support) for support requests in the future, thanks.
