### ISSUE TITLE
[Feature Request] Add control to convert dBFS units to S-Units

### ISSUE THREAD

**Issue by rfrht** [csete/gqrx#664]
Currently, the GQRX signal meter provides dBFS units.

This RFE requests the addition of a checkbox in Input Controls that would change the signal meter from dBFS to S-Units, from 0 to 9+60

Learn more from https://en.wikipedia.org/wiki/S_meter.

**Comment by csete** [comment]
Gqrx shows dBFS because this is the only meaningful information that can be calculated from the available data.

Providing S-units or any other absolute measure would require a thorough calibration of the hardware device over its entire frequency range, plus detailed knowledge about the signal path in each device. That is practically impossible and most certainly unfeasible to do for the wide range of arbitrary hardware supported by gqrx.
